module.exports = {
  User: require('./User.model'),
  CreatorProfile: require('./CreatorProfile.model'),
  BrandProfile: require('./BrandProfile.model'),
  AgencyProfile: require('./AgencyProfile.model'),
  Session: require('./Session.model'),
  Booking: require('./Booking.model'),
  Campaign: require('./Campaign.model'),
  Application: require('./Application.model'),
  Transaction: require('./Transaction.model'),
  Donation: require('./Donation.model'),
  Review: require('./Review.model'),
  Notification: require('./Notification.model'),
  Category: require('./Category.model'),
  Community: require('./Community.model'),
  CommunityMembership: require('./CommunityMembership.model'),
  Conversation: require('./Conversation.model'),
  Message: require('./Message.model'),
  Gift: require('./Gift.model'),
  Post: require('./Post.model'),
};